services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:80
    command: "/start-reload.sh"
    environment:
      VERSION: "latest"
      APP_MODULE: "app.main:app"
      LOG_LEVEL: "debug"
      ACCESS_LOG: "/dev/null"
      APP_NAME: "Utkarsh's Document Classifier FastAPI"
      # ------------ document classifier -------------------
      MODEL_NAME: pandit56625/fine-tuned-rvl-cdip
      TOKENIZER_NAME: microsoft/layoutlmv3-base

    volumes:
      - ./app:/code/app
